### ISSUE TITLE
the "sheet" problem

### ISSUE THREAD

**Issue by Lypzis** [zxzsaga/xlsx-json#3]
It's not actually a problem with the code (it may be), but I would like to know what is the "sheet" that is necessary for the script to work, you gave no hint in your tutorial. if you can please clarify, I will be gratefull.

**Comment by zxzsaga** [comment]
“sheet” is the sheet name in your xlsx file. A xlsx file may contain several sheets. It's in the bottom left corner in Excel.

**Comment by Lypzis** [comment]
ohh, many thanks, it finally worked.

is it possible to get a json list with each object like this? 
[{
	"name": "",
	"email": "",
	"c" : {
		"num" : "",
		"cr" : ""
	}
}, ...]

the table is like: 

name| email | c.num| c.cr
a       | a@    | 1         | aa
b      |  b@    |  2        | bb
...
